//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalkulatorPlace_zavrsni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        public string OIB { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Postanski_broj_i_grad { get; set; }
        public string Adresa_prebivalista { get; set; }
        public Nullable<int> Broj_djece { get; set; }
        public string Bankovni_racun { get; set; }
    }
}
